//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.6
//
// <auto-generated>
//
// Generated from file `hello.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.bglmmz.ice.demo.helloworld.slice;

/** @hidden */
public class _HelloServicePrxI extends com.zeroc.Ice._ObjectPrxI implements HelloServicePrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
